### PR TITLE
Update to upstream ecmwf/fckit-0.6.3 with support for eckit-1.1.0

### PR DESCRIPTION
**Pull request by markjolah**
With the changes suggested in this morning's meeting and those cherry-picked from branch `oops/bugfix/fckitmpi`, we we have been able to properly merge the latest tagged version from upstream `ecmwf/fckit-0.6.3`.  This version works with `eckit-1.1.0`.  I attempted to minimize the differences between our fork and upstream.

This branch should be used together with the `feature/eckit-1.1.0` branches in the other repos.  Master tracking issue is [jedi-stack#32](https://github.com/JCSDA/jedi-stack/issues/32).

### CODE REVIEW

**Comment by markjolah** [comment]
Hmm... sorry it looks like my changes and those of the ecmwf version update got merged into the same commit.  It's been a mess trying to keep up with all the different PRs and merges today.  I can redo this if it will be clearer or more useful.

**Comment by markjolah** [comment]
Here is the current diff between the ECMWF and JCSDA versions: [jcsda-fckit-0.6.3.diff.txt](https://github.com/JCSDA/fckit/files/3404107/jcsda-fckit-0.6.3.diff.txt)

**Comment by srherbener** [comment]
Thanks for posting the diffs. I think they are okay, so I'll keep the "Approve" for my review.

**Comment by danholdaway** [comment]
With Intel on Discover and Theia I get the following error building fckit:

```
/scratch4/NCEPDEV/da/save/Daniel.Holdaway/JediDev/fv3-bundle/fckit/src/tests/test_configuration.F90(324): error #8485: There is no matching specific function for this type bound generic function reference.   [GET]
  if( config%get("variables",variables) ) then
```

Also question, if I go to make a pull request of this branch into ecmwf develop it says there are conflicts. Shouldn't we be trying to get to a point of being able to merge our changes back to ECMWF with this PR?

**Comment by danholdaway** [comment]
By the way it builds just fine with gcc on Discover but sometimes gcc is more relaxed about things being undefined.

**Comment by markjolah** [comment]
Maybe @mmiesch or @ytremolet have some insight into this?  I am a little bit lost on these generic Fortran function interfaces.  At least with C/C++ error messages they list the types that the compiler is expecting.

**Comment by mmiesch** [comment]
I'm compiling with intel 18 on S4 now.  Just finished the stack and now working on ufo-bundle.  I'll take a look at that function interface - it should be easy to fix.  I'll also look into the conflicts.

**Comment by mmiesch** [comment]
So, I'm still having problems with this.  My latest push fixes the build problem that @danholdaway mentioned but the fckit_configuration_test still fails on S4 with intel18.  Even worse, the fckit_test_mpi and fckit_test_broadcast tests both hang - they don't even time out - just hang.  When I run with gnu 7.4 on AWS the mpi and broadcast don't hang but they fail (while fckit_configuration_test passes).  I'm also getting many bump test failures on AWS with gnu 7.4.  Is it possible to split up the eckit-1.1 PRs for oops and jedi-stack from the fckit-0.6.3 PRs on fckit and saber or do they all go together?

**Comment by markjolah** [comment]
I think we can probably work through the errors.  Some changes that have been made which should help narrow down the test failures:
 * [saber # 9](https://github.com/JCSDA/saber/pull/9) @benjaminmenetrier Fixed the mpi bump failures with a new C++ main for bump tests
 * [fckit # 11](https://github.com/JCSDA/fckit/pull/11) Fixed the fckit library dependencies
 * [oops # 316](https://github.com/JCSDA/oops/pull/316/files) Fixed the ordering of MPI and Log finalization in `oops::LibOOPS`

Currently I am passing all tests including fckit tests on AWS using the jedi-stack-v3 AMI.  I do
```
$ module load jedi/gnu-openmpi
$ module unload eckit/0.23.0
```
Then I enable eckit TAG 1.1.0 in the bundle.

I will look into testing with intel tomorrow or friday.

**Comment by markjolah** [comment]
There are also some minor test failures in saber with clang and gnu-9.1.0.  See: [saber # 15](https://github.com/JCSDA/saber/issues/15) for details.  These don't appear to be related to eckit/fckit.
